# Generated by Django 5.0.6 on 2024-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('butterfly_image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, default='none', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Specie',
                'ordering': ['scientific_name'],
            },
        ),
    ]
