# Generated by Django 5.0.7 on 2024-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='none', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Specie',
                'ordering': ['scientific_name'],
            },
        ),
    ]
