# Generated by Django 5.0.6 on 2024-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='butterfly_image',
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
